stdlib: Fix `strerror` error caused by exceeding the BPF stack limit.
This commit does two things:

1. Filter out invalid index of `errors[]`, (`errors[41]`, `errors[58]`).
2. Fix `strerror` error caused by exceeding the BPF stack limit.

For example:

    tracepoint:syscalls:sys_exit_openat,
    tracepoint:syscalls:sys_exit_openat2
    {
      $ret = args.ret;
      $fd = ($ret >= 0) ? $ret : (-1);
      $errno = ($ret >= 0) ? 0 : (-$ret);
      printf("%-6d %-16s %4d %3s\n", pid, comm, $fd, strerror($errno));
    }

    Error:
    error: <unknown>:0:0: in function tracepoint_syscalls_sys_exit_openat_1 i64 (ptr): Looks like the BPF stack limit is exceeded. Please move large on stack variables into BPF per-cpu array map. For non-kernel uses, the stack can be increased using -mllvm -bpf-stack-size

    (see llvm:llvm/lib/Target/BPF/BPFRegisterInfo.cpp::BPFStackSizeOption)

Signed-off-by: Rong Tao <rongtao@cestc.cn>