Fix compile error: bcc_elf.c: undefined reference to `debuginfod_begin'
If libdebuginfod is installed on the system and bpftrace is compiled with static
linking to BCC (STATIC_BPF_BCC), then libbcc.a requires the dynamic library
-ldebuginfod, in which case a compilation error will be reported if bpftrace is
compiled without linking libdebuginfod.

checkout bcc to commit 8c0272979e40("Allow libdebuginfod to be excluded even if
present") and disable libdebuginfod in build-libs.sh, solved undefined reference
to `debuginfod_begin' compile error.

How to reproduce the error:

$ sudo dnf install -y elfutils-debuginfod*
$ cd bpftrace
$ mkdir build && cd build
$ ../build-libs.sh
$ cmake -DCMAKE_INSTALL_PREFIX=/usr/ -DCMAKE_BUILD_TYPE=Debug ..
$ make -j$(nproc)
...
[ 91%] Linking CXX executable bpftrace
[ 92%] Linking CXX executable bpftrace_test
/usr/bin/ld: ../build-libs/lib64/libbcc.a(bcc_elf.c.o): in function `find_debug_file':
bcc_elf.c:(.text+0x10df): undefined reference to `debuginfod_begin'
/usr/bin/ld: bcc_elf.c:(.text+0x10fd): undefined reference to `debuginfod_find_debuginfo'
/usr/bin/ld: bcc_elf.c:(.text+0x1110): undefined reference to `debuginfod_end'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/bpftrace.dir/build.make:121: src/bpftrace] Error 1
make[1]: *** [CMakeFiles/Makefile2:1328: src/CMakeFiles/bpftrace.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: ../build-libs/lib64/libbcc.a(bcc_elf.c.o): in function `find_debug_file':
bcc_elf.c:(.text+0x10df): undefined reference to `debuginfod_begin'
/usr/bin/ld: bcc_elf.c:(.text+0x10fd): undefined reference to `debuginfod_find_debuginfo'
/usr/bin/ld: bcc_elf.c:(.text+0x1110): undefined reference to `debuginfod_end'
collect2: error: ld returned 1 exit status
make[2]: *** [tests/CMakeFiles/bpftrace_test.dir/build.make:364: tests/bpftrace_test] Error 1
make[1]: *** [CMakeFiles/Makefile2:2230: tests/CMakeFiles/bpftrace_test.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

Link: https://github.com/iovisor/bpftrace/pull/2411
Signed-off-by: Rong Tao <rongtao@cestc.cn>