Some small fixes in various parts of bpftrace. (#4698)
* Fix off-by-one for function argument size comparison

Commit 4e2f3c793458 ("arch: ensure all code is built all the time")
removed the arch::max_arg function and replaced its usage with
arch::Host::arguments().size().

max_arg defined the maximum argument number (so, 0-based), unlike
arch::Host::arguments().size(), which is the size of the array.

The comparisons against this value were thus converted from > to >=.
However, comparisons to max_arg() + 1 were also converted to >=,
which is incorrect - they can stay the same, as max_arg + 1 is
equal to arch::Host::arguments().size().

This lead to BTF functions with the maximum number of
register-passed arguments to be incorrectly rejected for use
in fentry probes.

Change these comparisons back. Also fix an adjacent warning
to not hardcode '6' (the x86 value) for the maximum number.

Fixes: 4e2f3c793458 ("arch: ensure all code is built all the time")
Signed-off-by: Frank van der Linden <fvdl@google.com>

* explicitly include iostream in opaque.cpp

Explicitly include iostream, or, depending on the environment, clang
might throw an error like:

error: invalid operands to binary expression ('std::ostream' (aka
'basic_ostream<char>') and 'ios_base &(ios_base &)')

Signed-off-by: Frank van der Linden <fvdl@google.com>

* tests: skip resolve_timestamp test if < ns precision

The resolve_timestamp test assumes that system_clock has
nanosecond precision. Which is a reasonable assumption
for most Linux environments. But there are some that
do not offer system_clock with that precision. Just skip
the test in that case.

Signed-off-by: Frank van der Linden <fvdl@google.com>

---------

Signed-off-by: Frank van der Linden <fvdl@google.com>
Co-authored-by: Frank van der Linden <fvdl@google.com>