bpftrace: Fix compilation error
FatalUserException() is now relocated to util/exceptions.h. However, the
header file is not updated accordingly in arch specific files. This
leads to the following compilation error:
bpftrace/src/arch/s390.cpp:2:10: fatal error: utils.h: No such file or directory
2 | #include "utils.h"
  |          ^~~~~~~~~

Fix compilation error by adjusting the headers in architecture specific files.

Fixes: f3557db5 ("cleanup: split `utils.cpp` into `util` library")
Signed-off-by: Sumanth Korikkar <sumanthk@linux.ibm.com>