fix tracepoint format parser bug
Address issue #364

Inside TracepointFormatParser::parse(), std::ifstream::fail() checks the
validity of a tracepoint event path. Unfortunately, ifstream cannot handle
wildcards so the one-liner below is broken:

    $ bpftrace -e 'tracepoint:syscalls:sys_enter_* { @[probe] = count(); }'
    ERROR: tracepoint not found: syscalls:sys_enter_*

In this case ifstream::fail() will always be true.

Since ifstream fails to handle wildcards we use glob() instead. And in
get_tracepoint_struct() the real event name is used, not the wildcard one.

Signed-off-by: Xiaozhou Liu <liuxiaozhou@bytedance.com>