clang-format: exclude JSON files
Running `git clang-format` on commits changing JSON files fails with:

    Configuration file(s) do(es) not support Json: /home/runner/work/bpftrace/bpftrace/.clang-format
    error: `clang-format -lines=1:5 tests/runtime/outputs/delete_wildcard_idx_0.json` failed

We don't need to run clang-format on JSON files so just ignore them.