Call llvm.lifetime.end after memcpy if the expression is not a variable
Call llvm.lifetime.end after a temporal buffer (AllocaInst object) is
used so that the buffer is freed for the following cases.

- ternary
  - ex) `$a = cond ? @x : @y`
- assignvalue
  - ex) `$a = @x`
- printf
  - ex) `printf("%s\n", @a)`
- strncmp
  - ex) `strcmp("sshd", comm)`
- getMapKey
  - ex) `@[comm]`
- getHistMapKey
  - ex) `@[comm] = hist(1)`

Note that a map access (`CreateMapLookupElem`) and `comm` return a
temporal buffer. As of mapassign, a buffer is already freed after use.

This patch fixes, for example, the following error:

```
% bpftrace -e 'BEGIN { @x = "foo"; unroll(10) { printf("%s\n", @x);} }'
error: <unknown>:0:0: in function BEGIN i64 (i8*): Looks like the BPF stack limit of 512 bytes is exceeded. Please move large on stack variables into BPF per-cpu array map.
```