Warn on low log space in verbose mode (#5259)
Prompt a message when there is insufficient log space in verbose mode.
This will let the user know what may have happened and allow them to
make adjustments.

Normally, logging is not used by default (log_level=0). However, in
verbose mode, enabling logging may cause failure (ENOSPC). This can
cause the same command or script to succeed in non-verbose mode but
fail in verbbose mode, which can confuse users.

For example (source code [1]):
    $ sudo ./str_concat.bt # success
    $ sudo ./str_concat.bt -v # failed (Users will be very confused)
    ....
    ERROR: Error loading BPF program for begin_1. Error code: -28.
    Kernel error log:
    processed 87034 insns (limit 1000000) max_states_per_insn 4 total_states 2811 peak_states 136 mark_read 31

Because in this situation, the kernel log only contains one line
`processed N insns (limit 1000000)`, so is_log_trimmed() will fail.
We can solve this by adding a condition `res == -ENOSPC`.

If the error is ENOSPC, prompt the user to set a larger log space:

    $ sudo ./str_concat.bt -v # failed (but give some advice)
    ....
    ERROR: Error loading BPF program for begin_1. Error code: -28 (No space left on device).
    Kernel error log:
    processed 87034 insns (limit 1000000) max_states_per_insn 4 total_states 2811 peak_states 136 mark_read 31

    WARNING: Kernel log seems to be trimmed. This may be due to buffer not being big enough, try increasing the BPFTRACE_LOG_SIZE environment variable beyond the current value of 1000000 bytes. Or, add the configuration `config = { log_size = N; }` to the script.

[1] https://github.com/bpftrace/bpftrace/pull/5259

Signed-off-by: Rong Tao <rongtao@cestc.cn>