AttachPointParser: Error handling improvements
- Ensure integer parsing errors end in new lines
- Parse signed integers when requested (not always unsigned)
- Early returns from sto[u]ll parsing errors to reduce nesting
- Ensure non-fatal errors do not get displayed

Attempting to parse a string with stoll can result in a non-fatal error
when parsing uprobes, as they are allowed to accept either an address or
a function name. This stoll error should never be displayed to the user.

Previously, when the error buffer was not cleared between attachpoints,
if the next attachpoint had a fatal error then this non-fatal stoll
error would also be displayed.

Due to a combination of the now-fixed problems, the error message for
the new test case used to be:

  ERROR: Coefficient part of scientific literal is not a valid number: Str: stoulltracepoint probe type requires 2 arguments

Note the missing newline and the non-fatal first error.