btf: improve anonymous struct/union handling
In BTF::get_stype, a simple None type is returned if the type
is found to be an anonymous struct/union. There is no way to
resolve this later, so this results in errors when accessing
fields of anonymous structures, e.g:

fentry:zone_reclaimable_pages
{
    printf("%lu\n", args.zone->vm_stat[NR_FREE_PAGES].counter);
}

This yields:

ERROR: Can not access field 'counter' on expression of type 'none'

This is because vm_stat is an array of atomic_long_t inside of
struct zone, and atomic_long_t is an anonymous struct with one field
('counter'). Since this anonymous struct is set to None in
BTF:get_stype, an error will always occur.

Structures/unions are managed by name, through struct.Lookup or
struct.LookupOrAdd. This wouldn't work with anonymous struct/unions.
To make life simpler, just generate an unlikely name for these
record types, containing the BTF id and the name of the BTF object
they came from. This allows maintaining them as normal record types,
as their information can be resolved by parsing the name.

The name format is: BTF_ANON_STRUCT_PREFIX + <btfid> + "_" + <btfobjname>,
where BTF_ANON_STRUCT_PREFIX is "__BpFtRaCe_btf_anon_"

Signed-off-by: Frank van der Linden <fvdl@google.com>