CI: Use fetch-depth 0 for Binary workflow (#5304)
Recently, we started getting the following failure for the Binary CI
workflows on pull requests:

    nix build .?submodules=1#appimage
    cp ./result bpftrace
    shell: /usr/bin/bash -e {0}
    env:
      DETSYS_BACKTRACE_COLLECTOR: e5e28c06-d6d6-410e-90e3-e02e8d09333f
      DETERMINATE_NIX_KVM: 1
      MAGIC_NIX_CACHE_DAEMONDIR: /home/runner/work/_temp/magic-nix-cache-fb9be037-81ea-40cc-962c-57e0c180f2dd
    error:
         … while fetching the input 'git+file:///home/runner/work/bpftrace/bpftrace?shallow=1&submodules=1'

         … while fetching the input 'git+file:///home/runner/work/bpftrace/bpftrace/libbpf?submodules=1'

         error: '/home/runner/work/bpftrace/bpftrace/libbpf' is a shallow Git repository, so 'revCount' is not available
    Error: Process completed with exit code 1.

Interestingly, it only happens on pull requests. The reason seems to be
that the checkout action by default performs shallow clones on
submodules. Set fetch-depth to 0 to perform full clone.

Signed-off-by: Viktor Malik <viktor.malik@gmail.com>
(cherry picked from commit dc9d708e3726d0206b0097d981adb19b312cb232)