c++20: don't use std::format()
On debian12(gcc 12.2.0, llvm 19.1.14):

    ....
    [ 18%] Building CXX object src/ast/CMakeFiles/ast.dir/passes/macro_expansion.cpp.o
    /home/rongtao/Git/bpftrace/bpftrace/src/ast/passes/macro_expansion.cpp:1:10:
    fatal error: format: No such file or directory
        1 | #include <format>
          |          ^~~~~~~~
    compilation terminated.

    ....
    [ 82%] Building CXX object src/ast/CMakeFiles/ast.dir/passes/unstable_feature.cpp.o
    /home/rongtao/Git/bpftrace/bpftrace/src/ast/passes/unstable_feature.cpp:2:10:
    fatal error: format: No such file or directory
        2 | #include <format>
          |          ^~~~~~~~
    compilation terminated.

gcc-13-3936-g1d9454aba615 and llvmorg-13-init-172-g081c1db02dd2 introduce
format header. Because the clang/gcc version judgment conditions are more
complicated, it is a good solution to directly replace std::format with
std::string concatenation.

Link: https://github.com/gcc-mirror/gcc/commit/1d9454aba615
Link: https://github.com/llvm/llvm-project/commit/081c1db02dd2
Signed-off-by: Rong Tao <rongtao@cestc.cn>