apparser: kfunc: Report better errors for missing comma
Given the following script (that's missing a comma):

```
kfunc:xfrm4_esp_rcv
kfunc:xfrm4_rcv
{
    exit()
}
```

you get this error:

```
Attaching 1 probe...
ERROR: No BTF found for xfrm4_rcv
```

which is too vague.

This is b/c the parser effectively ignores spaces and combines the two
attachpoints into one string (sans space) when creating the
input to AttachPointParser. This is an unfortunate result of the
attachpoint parser design.

It's a bit too unwieldy to teach the parser about spaces (cuz we'd have
to sprinkle it everywhere), so opt to do the next best thing and have a
slightly more informative error instead.

With this commit, the error is now:

```
Attaching 1 probe...
ERROR: No BTF found for xfrm4_esp_rcvkfunc:xfrm4_rcv
```

which should provide a better hint to the user.