CreateMemSet: llvm10: Fix compilation errors
The following llvm commit:
"[Alignment][NFC] CreateMemSet use MaybeAlign" (https://reviews.llvm.org/D71213)
changed the signature of CreateMemSet() function, which causes the following
compilation errors:

...
src/ast/irbuilderbpf.cpp:85:52: error: no matching function for call to 'bpftrace::ast::IRBuilderBPF::CreateMemSet'
   85 |     CreateMemSet(alloca, getInt64(0), stype.size, 1);
      |
...

Use LLVM_VERSION_MAJOR macro to select the appropriate call.

Fixes: #1165
Signed-off-by: Ovidiu Panait <ovidiu.panait@windriver.com>