Error if wildcards are used in "category" of tracepoint
Currently, TracepointFormatParser::parse() does not expand wildcards in "category". This leads to an incorrect event name.
https://github.com/iovisor/bpftrace/blob/24f97308895078fe0130a58e0cf5703f4de975a9/src/tracepoint_format_parser.cpp#L73-L75

Check if wildcards are used in "category" and return an error in that case.
For example:

```
% sudo ./src/bpftrace -e 'tracepoint:sys*:*{args;}'
ERROR: wildcard in tracepoint category is not supported: sys*
```