stdlib: Fix `strerror` error caused by exceeding the BPF stack limit. (#5096)
    Error:
    error: <unknown>:0:0: in function tracepoint_syscalls_sys_exit_openat_1 i64 (ptr): Looks like the BPF stack limit is exceeded. Please move large on stack variables into BPF per-cpu array map. For non-kernel uses, the stack can be increased using -mllvm -bpf-stack-size

    (see llvm:llvm/lib/Target/BPF/BPFRegisterInfo.cpp::BPFStackSizeOption)


(cherry picked from commit b5b328e44066858b5146cf5027ded71e5c46d906)

Signed-off-by: Rong Tao <rongtao@cestc.cn>
Co-authored-by: Rong Tao <rongtao@cestc.cn>