arm: Add -D__LINUX_ARM_ARCH__=7 to kernel cflags
This is normally set in KBUILD_CFLAGS based on the target CPU and kernel headers
in arm/include rely on it. Since those get included by other non-UAPI headers,
we need to set it as well to avoid errors like this:

  # bpftrace --include linux/fs.h -e 'BEGIN {}'
  arch/arm/include/asm/spinlock.h:6:2: error: SMP not supported on pre-ARMv6 CPUs
  arch/arm/include/asm/cmpxchg.h:114:2: error: "SMP is not supported on this platform"
  include/asm-generic/cmpxchg.h:8:2: error: "Cannot use generic cmpxchg on SMP"
  arch/arm/include/asm/atomic.h:146:2: error: SMP not supported on pre-ARMv6 CPUs