type_resolver: Set user address space for USDT arguments
* bpftrace --verify-llvm-ir -e 'usdt:./build/tests/testprogs/usdt_test:* { $a = str(arg1); }'
ERROR: Addrspace is not set

usdt arguments are handled differently from kprobe/uprobe arguments:

1. kprobe/uprobe: arg0, arg1 are builtins that get address space from
   find_addrspace(probetype), which returns kernel/user based on probe type.

2. usdt: arg0, arg1 are replaced by the USDTArgumentLift pass
   (src/ast/passes/usdt_arguments.cpp) with calls to usdt_arg() macro,
   which expands to __usdt_arg().

Explicitly set uptr() for __usdt_arg() return type, since usdt
arguments always come from user space.

Suggested-by: Ilya Leoshkevich <iii@linux.ibm.com>
Reviewed-by: Ilya Leoshkevich <iii@linux.ibm.com>
Signed-off-by: Sumanth Korikkar <sumanthk@linux.ibm.com>