Add LIBBPF_LIBRARIES to bpf_attach_kprobe build
When using libbcc-no-libbpf.so as bcc library,
we need to link the test also with libbpf.so,
otherwise the test compilation fails on missing
libbpf symbols.

/usr/bin/c++   -DLIBBCC_ATTACH_KPROBE_SIX_ARGS_SIGNATURE  \
 CMakeFiles/cmTC_ddd8d.dir/src.cxx.o  -o cmTC_ddd8d       \
 -Wl,-rpath,/opt/bcc/lib64 /opt/bcc/lib64/libbcc-no-libbpf.so
/usr/bin/ld: /opt/bcc/lib64/libbcc-no-libbpf.so: undefined reference to `ring_buffer__poll@LIBBPF_0.0.9'
/usr/bin/ld: /opt/bcc/lib64/libbcc-no-libbpf.so: undefined reference to `ring_buffer__new@LIBBPF_0.0.9'
/usr/bin/ld: /opt/bcc/lib64/libbcc-no-libbpf.so: undefined reference to `ring_buffer__add@LIBBPF_0.0.9'
/usr/bin/ld: /opt/bcc/lib64/libbcc-no-libbpf.so: undefined reference to `ring_buffer__consume@LIBBPF_0.0.9'
/usr/bin/ld: /opt/bcc/lib64/libbcc-no-libbpf.so: undefined reference to `ring_buffer__free@LIBBPF_0.0.9'

Signed-off-by: Jiri Olsa <jolsa@redhat.com>