Emit better tracepoint parser errors
Before, we were only doing our nice tracepoint error checks if the tp
args was used. We can make our error messages a little better if we do
all the work except actually parse the format file.

Before:

    $ sudo bpftrace -e 'tracepoint:syscall:sys_enter_nanosleepz { 1 }'
    Attaching 1 probe...
    open(/sys/kernel/debug/tracing/events/syscall/sys_enter_nanosleepz/id):
    No such file or directory
    Error attaching probe: tracepoint:syscall:sys_enter_nanosleepz

After:

    $ sudo bpftrace -e 'tracepoint:syscall:sys_enter_nanosleepz { 1 }'
    ERROR: tracepoint not found: syscall:sys_enter_nanosleepz
    Did you mean syscalls:sys_enter_nanosleepz?