semantic_analyser: fix gcc build error on xenial
The following error is happening on xenial (with gcc 5.4.0):

  ./src/ast/semantic_analyser.cpp:1003:3: error: converting to ‘const std::tuple<long unsigned int, bool>’ from initializer list would use explicit constructor ‘constexpr std::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = int; _U2 = bool; <template-parameter-2-3> = void; _T1 = long unsigned int; _T2 = bool]’
     };
     ^

Using Uniform initialization instead of implicit initializer_list to
tuple casting fixes the issue.