arm64: define the KASAN_SHADOW_SCALE_SHIFT macro
arm64 defines this macro from Makefile instead of defining it in a
header file as is the case for other architectures. Since we're not
running make, we need to define the macro manually via CFLAGS.

The value definition is taken from kernel's arch/arm64/Makefile and it
depends on the running kernel configuration.

This fixes the runqlat.bt tcpdrop.bt, and undump.bt tools on
aarch64+debug kernel which previously failed with:

    # /usr/share/bpftrace/tools/runqlat.bt
    [...]/source/arch/arm64/include/asm/memory.h:300:9: error: use of undeclared identifier 'KASAN_SHADOW_SCALE_SHIFT'
    [...]