Auto-include headers for imported C
When using import to include C code in a bpftrace script, if this C
code depends on header files in the current directory, we also need
to import the header files in the bpftrace script; otherwise, the
header files won't exist in llvm::vfs::InMemoryFileSystem, as shown
in the example below:

    // a.bpf.h
    #pragma once
    #define ONE 1

    // a.bpf.c
    #include "a.bpf.h"
    int one(void) {
      return ONE;
    }

    // a.bt
    import "a.bpf.c";
    begin {
      printf("%d\n", one());
    }

Then, run script:

    $ sudo ./a.bt
    1 error generated.
    /home/rongtao/Git/tst-linux/bpf/bpftrace/samples/import/a.bt:3:1-17: ERROR: failed to build
    import "a.bpf.c";
    ~~~~~~~~~~~~~~~~
    HINT: a.bpf.c:1:10: fatal error: 'a.bpf.h' file not found
        1 | #include "a.bpf.h"
          |          ^~~~~~~~~

We have to import "a.bpf.h" to fix this issue. But actually, a.bpf.c
has already included a.bpf.h, so we should avoid letting import bring
it in again.

This submission automatically adds all .h files in the current
directory to clang's virtual file system, so they can be #include'd
directly in .c files without any extra import steps.

Signed-off-by: Rong Tao <rongtao@cestc.cn>