Fix: privilege check
The call to check_privileges needs to be moved above the call to
symbols::KernelInfoImpl::open or else if bpftrace is run without sudo or
the correct privileges we get this error:

ERROR: Failed to open kernel function info: Error reading events from
/sys/kernel/debug/tracing/available_events (Permission denied)

This actually begs a larger question if our more fine-grained privilege
check is useless if we can't read this file without root - will look into
this in a follow-up.

Signed-off-by: Jordan Rome <linux@jordanrome.com>