clang-tidy: Enable some more bugprone-* checks
These seem pretty reasonable to turn on. Particularly the use-after-move
one. It caught this existing error:

```
/home/dlxu/dev/bpftrace/src/ast/passes/field_analyser.cpp:217:13: error: 'probe_args' used after it was moved [bugprone-use-after-move,-warnings-as-errors]
  217 |         if (probe_args.size == -1)
      |             ^
/home/dlxu/dev/bpftrace/src/ast/passes/field_analyser.cpp:261:25: note: move occurred here
  261 |       bpftrace_.structs.Add(probe.args_typename(), std::move(probe_args));
      |                         ^
/home/dlxu/dev/bpftrace/src/ast/passes/field_analyser.cpp:217:13: note: the use happens in a later loop iteration than the move
  217 |         if (probe_args.size == -1)
```

It looks like `probe_args` doesn't actually need to be preserved across
different iterations of the outer loop. So just move
declaration/initialization inside the loop to avoid undefined moved-from
state.