CMake: Fix circular static library dependencies
Some internal static libraries may have subtle circular dependencies.
In particular:
- attachpoint_passes.cpp uses Dwarf from dwarf_parser.cpp
- attachpoint_passes.cpp is in the `ast` target which is normally linked
  *after* the `runtime` target

This may lead to the following linker error:

  /usr/bin/ld.bfd: ast/libast.a(attachpoint_passes.cpp.o): [...]
  [...] undefined reference to `bpftrace::DwarfParseError::ID'

Fix the issue by wrapping the linked libraries with `--start-group` and
`--end-group`, which allows the linker to resolve the dependencies
properly.

Signed-off-by: Viktor Malik <viktor.malik@gmail.com>

stack-info: PR: https://github.com/bpftrace/bpftrace/pull/5166, branch: user/viktormalik/docker-opensuse/1