clang_parser: workaround for asm_inline in 5.4+ kernel headers
Upstream kernel introduced `asm_inline` in:
https://github.com/torvalds/linux/commit/eb111869301e15b737315a46c913ae82bd19eb9d

However, clang doesn't support this, so we redefine `asm_inline` to `asm`.
BCC introduced this workaround in:
https://github.com/iovisor/bcc/commit/2d1497cde1cc9835f759a707b42dea83bee378b8

Here is the same workaround for bpftrace.

The following errors occur without this workaround:
```
$ sudo /usr/share/bpftrace/tools/runqlat.bt
/lib/modules/5.4.12-200.fc31.x86_64/source/arch/x86/include/asm/segment.h:266:2: error: expected '(' after 'asm'
/lib/modules/5.4.12-200.fc31.x86_64/source/arch/x86/include/asm/page_64.h:49:2: error: expected '(' after 'asm'
/lib/modules/5.4.12-200.fc31.x86_64/source/arch/x86/include/asm/special_insns.h:205:2: error: expected '(' after 'asm'
```

Thanks to Ivan Babrou for the original workaround in BCC, and to fbs to show me where to apply this workaround in bpftrace.