Fix listing for type definitions and scripts
Commit e8bbee4 ("[#3058] fix bpftrace -l test.bt (#3111)") broke listing
of struct definitions:

    # bpftrace -l 'struct task_struct'
    ERROR: failed to open file 'struct task_struct': No such file or directory

This fixes the above problem by clearing up how bpftrace distinguishes
differents kinds of listing:
- if the search entry is an existing file, it is interpreted as such,
- if the search entry starts with "struct ", "union ", or "enum "
  (notice the trailing spaces), it is interpreted as a type name,
- otherwise the search entry is interpreted as a probe. In this case,
  when the search entry contains a dot ('.') and does not contain a
  wildcard ('*') or a colon (':'), a warning is shown that such a file
  does not exist.

Also introduce a runtime test for type listing to avoid future breakage.