Decouple kheaders unpacking from BTF support
This is a partial revert of 17bbcd2b0 ("kheader: Do not unpack kheaders if
system has BTF"). Checking if the kernel supports BTF is not sufficient, as
ClangParser may decide to not use the BTF-generated header in case there are
conflicts with user-defined types[1].

For example, the following script falls back on kernel headers, which on a
system that relies on CONFIG_IKHEADERS (e.g. Android) produces this error:

  $ sudo bpftrace -
  struct task_struct {}   // redefinition
  struct foo { struct task_struct dummy; }
  BEGIN {}
  ^D
  /bpftrace/include/clang_workarounds.h:14:10: fatal error: 'linux/types.h' file not found

This also unbreaks scripts written for older kernels without BTF support
that unconditionally include kernel headers.

[1] https://github.com/iovisor/bpftrace/blob/3c417c8e3792c58a5958e3b1c49958ac063667a8/src/clang_parser.cpp#L765