Fix: privilege check (#5097)
The call to check_privileges needs to be moved above the call to
symbols::KernelInfoImpl::open or else if bpftrace is run without sudo or
the correct privileges we get this error:

ERROR: Failed to open kernel function info: Error reading events from
/sys/kernel/debug/tracing/available_events (Permission denied)

This actually begs a larger question if our more fine-grained privilege
check is useless if we can't read this file without root - will look into
this in a follow-up.

Signed-off-by: Jordan Rome <linux@jordanrome.com>
Co-authored-by: Jordan Rome <linux@jordanrome.com>
(cherry picked from commit 95526389a2f0f9a2a2981616af8dcd279732f938)