Update 'check_alignment'
Remove HAVE_UNSAFE_PROBE compiler flag. This seems
redundant at best since the safe mode is the default
and I can't seem to find reasoning for it when it was added:
https://github.com/bpftrace/bpftrace/commit/18b96356408392e7330d3e95ef871088c00c6c97

Also remove 'check_alignment' for kprobes as the
kernel gives a nice error message if you try to add
a probe in the middle of an instruction:
```
ERROR: Possible attachment attempt in the middle of an instruction, try a different offset.
ERROR: Error attaching probe: kprobe:do_nanosleep+2
```