add <string> in opaque.h (#4872)
Add <string> in opaque.h, to avoid the following error when
building tests/opaque.cpp in a build environment that is
strict(er) about transitive/implicit includes

util/opaque.h:54:39: error: implicit instantiation of undefined template
'std::basic_string<char>'

Signed-off-by: Frank van der Linden <fvdl@google.com>
Co-authored-by: Frank van der Linden <fvdl@google.com>
(cherry picked from commit 4aad30964fba4dfcee9f12d171c27a3da0716a25)