Config: fail on invalid cache_user_symbols
When an invalid value is passed to the "cache_user_symbols" config
option, we print an error but do not fail b/c the error is not printed
to ConfigAnalyser::err_. Since the method for setting the value is
called from other places than ConfigAnalyser (when setting the option
from env), let's keep the current behaviour but add an extra empty

    LOG(ERROR, assignment.expr->loc, err_);

to ConfigAnalyser. This will make ConfigAnalyser fail and also print the
error location:

    ERROR: Invalid value for cache_user_symbols: valid values are PER_PID, PER_PROGRAM, and NONE.
    stdin:1:33-41: ERROR:
    config = { cache_user_symbols = "PERPID" } u:/bin/bash:readline { exit(); }

This a bit of a hack and the output is not super-nice but it's the
cleanest thing code-wise.