Fix linking against libbpf.a
Commit 85d25d06 ("fix: libbpf.a symbols shadow by libbcc_bpf.so
(#4429)") added explicit linking against libbpf.a to prevent dynamic
libbpf linked by bcc from shadowing symbols in the static libbpf (which
we need). However, since just `libbpf.a` is used, target_link_libraries
will prefer system static libbpf over custom-installed one. This may
lead to compilation errors such as:

    [ 95%] Linking CXX executable bpftrace
    /usr/bin/ld: /usr/local/lib64/libbpf.a(str_error.o): in function `libbpf_strerror_r':
    ~/src/bpf/libbpf/src/str_error.c:21: multiple definition of `libbpf_strerror_r'; /usr/lib/gcc/x86_64-redhat-linux/15/../../../../lib64/libbpf.a(str_error.o):(.text+0x0): first defined here

Use `${LIBBPF_LIBRARIES}` instead of `libbpf.a` to fix the issue.

Signed-off-by: Viktor Malik <viktor.malik@gmail.com>