Fix parse_modules() to handle kernels without modules
On kernels built with CONFIG_MODULE=n, bpftrace fails like this:

    # bpftrace -e 'kprobe:acpi_os_read_port { @[kstack] = count(); }'
    ERROR: Failed to open kernel function info: Error reading modules
    from /proc/modules (No such file or directory)

Simply returning {"vmlinux"} as the set of modules when /proc/modules
does not exist fixes the problem.

Signed-off-by: Calvin Owens <calvin@wbinvd.org>