Release/0.23.3 (#4177)
* tools/runqlen.bt: rename nr_running to nr_queued

With "sched/fair: Fix statistics with delayed dequeue" series (more
specifically torvalds/linux@736c55a02c47) several fields in "struct
cfs_rq" is renamed, leading to runqlen.bt to fail at runtime with the
following error:

  ERROR: Struct/union of type 'struct cfs_rq' does not contain a field named 'nr_running'
      $len = $my_q->nr_running;

Move existing runqlen script to tools/old/, create a copy of the original with
with nr_running changed to nr_queued in its place, and has GitHub CI use the
old version of runqlen for testing.

While at it, also touch up the comment regarding BTF.

Link: https://lore.kernel.org/all/20241202174606.4074512-1-vincent.guittot@linaro.org/
Signed-off-by: Shung-Hsi Yu <shung-hsi.yu@suse.com>

* Use BPF_ANY when initializing per-cpu map key/val

AFAICT, it doesn't matter if the key already exists
when initializing/updating a per-cpu map because
another CPU may have already added the key but the
CPU slot for that key should still be 0 or empty
if the check for that element fails on the same thread.

This also avoids showing the user an error
they can do nothing about:
https://github.com/bpftrace/bpftrace/issues/4068

Signed-off-by: Jordan Rome <linux@jordanrome.com>

* Fix tools/runqlat.bt warnings

The warning looks like:
sudo ./tools/runqlat.bt
Attaching 5 probes...
Tracing CPU scheduler... Hit Ctrl-C to end.
./tools/runqlat.bt:46:2-31: WARNING: Can't delete map element because it does not exist.
Additional Info - helper: map_delete_elem, retcode: -2
    delete(@qtime, args.next_pid);
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./tools/runqlat.bt:46:2-31: WARNING: Can't delete map element because it does not exist.
Additional Info - helper: map_delete_elem, retcode: -2
    delete(@qtime, args.next_pid);
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./tools/runqlat.bt:46:2-31: WARNING: Can't delete map element because it does not exist.
Additional Info - helper: map_delete_elem, retcode: -2
    delete(@qtime, args.next_pid);
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./tools/runqlat.bt:46:2-31: WARNING: Can't delete map element because it does not exist.
Additional Info - helper: map_delete_elem, retcode: -2
    delete(@qtime, args.next_pid);
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./tools/runqlat.bt:46:2-31: WARNING: Can't delete map element because it does not exist.
Additional Info - helper: map_delete_elem, retcode: -2
    delete(@qtime, args.next_pid);

Signed-off-by: Hui Su <sh_def@163.com>

* Fix firing order issue for fexit and software (#4113)

* Fix fexit firing order

Fixes: https://github.com/bpftrace/bpftrace/issues/4104

* Fix software firing order

Fixes: https://github.com/bpftrace/bpftrace/issues/4111

* Update CHANGELOG

---------

Signed-off-by: gray <greyschwinger@gmail.com>

* Fix execution watchpoints (#4139)

As per the perf_event_open man page,
we should be setting bp_len to `sizeof(long)`
for execution breakpoints.

https://man7.org/linux/man-pages/man2/perf_event_open.2.html

Issue: https://github.com/bpftrace/bpftrace/issues/4131

Signed-off-by: Jordan Rome <linux@jordanrome.com>
Co-authored-by: Jordan Rome <linux@jordanrome.com>

* Fix clang format

Signed-off-by: Jordan Rome <linux@jordanrome.com>

* Create 0.23.3 release

Signed-off-by: Jordan Rome <linux@jordanrome.com>

---------

Signed-off-by: Shung-Hsi Yu <shung-hsi.yu@suse.com>
Signed-off-by: Jordan Rome <linux@jordanrome.com>
Signed-off-by: Hui Su <sh_def@163.com>
Signed-off-by: gray <greyschwinger@gmail.com>
Co-authored-by: Shung-Hsi Yu <shung-hsi.yu@suse.com>
Co-authored-by: Jordan Rome <linux@jordanrome.com>
Co-authored-by: Hui Su <suhui@zeku.com>
Co-authored-by: graymon <greyschwinger@gmail.com>