ClangParser: Include enums in incomplete types
When collecting incomplete types to be resolved from BTF, account also
for enums. This is useful for resolving struct fields having enum types,
especially tracepoint args which use this code path:

    # bpftrace -lv 'tracepoint:syscalls:sys_enter_landlock_add_rule'
    tracepoint:syscalls:sys_enter_landlock_add_rule
        int __syscall_nr
        const int ruleset_fd
        const enum landlock_rule_type rule_type     <-- enum typed arg
        const void *const rule_attr
        const __u32 flags

Previously, the following script would fail:

    # bpftrace -e 'tracepoint:syscalls:sys_enter_landlock_add_rule { print(args.rule_type) }'
    definitions.h:14:33: error: field has incomplete type 'const enum landlock_rule_type'
    definitions.h:14:14: note: forward declaration of 'enum landlock_rule_type'

With this change, the type of `args.rule_type` is successfully resolved.

Signed-off-by: Viktor Malik <viktor.malik@gmail.com>
(cherry picked from commit f7fc3e3ede99a15c923e2f579a4aa24f1e06ee6c)