tools/runqlen.bt: rename nr_running to nr_queued
With "sched/fair: Fix statistics with delayed dequeue" series (more
specifically torvalds/linux@736c55a02c47) several fields in "struct
cfs_rq" is renamed, leading to runqlen.bt to fail at runtime with the
following error:

  ERROR: Struct/union of type 'struct cfs_rq' does not contain a field named 'nr_running'
      $len = $my_q->nr_running;

Move existing runqlen script to tools/old/, create a copy of the original with
with nr_running changed to nr_queued in its place, and has GitHub CI use the
old version of runqlen for testing.

While at it, also touch up the comment regarding BTF.

Link: https://lore.kernel.org/all/20241202174606.4074512-1-vincent.guittot@linaro.org/
Signed-off-by: Shung-Hsi Yu <shung-hsi.yu@suse.com>