AttachPointParser: Fix uprobe language component handling
Removed a condition that prevented inserting an empty string into the parts_ vector when PID and language were specified.

Previously, this caused the language part to be overwritten, thus losing the language information later. This could lead to failures in attaching probes correctly, for example, by breaking C++ demangling.

```
$ sudo ./bpftrace --pid '105772' -e 'uprobe:cpp:compute {
print("hello"); }'
ERROR: Could not resolve symbol: /proc/105772/root/home/user/foo:compute
ERROR: Unable to attach probe:
uprobe:/proc/105772/root/home/user/foo:compute. If this is expected, set
the 'missing_probes' config variable to 'warn'.
```

Signed-off-by: Marek Pazúr <marekpazur1@seznam.cz>